### ISSUE TITLE
WoW! wonderful . not a issues, 

### ISSUE THREAD

**Issue by trustfarm-dev** [sammy007/go-cryptonote-pool#4]
Wonderful , awesome works.
I'll try to in shortime and feedback.

Donation to 10ETC , your ETH donation address.
https://gastracker.io/tx/0x06e94dadcea9e8953af04cbda6666591c033fe664f653deb10adabb77c8fbf0a

**Comment by trustfarm-dev** [comment]
it's comments.

**Comment by sammy007** [comment]
Because https://en.wikipedia.org/wiki/KISS_principle

**Comment by trustfarm-dev** [comment]
YES GOOD . KISS ^^
