### ISSUE TITLE
Log pool hash

### ISSUE THREAD

**Issue by marku89** [sammy007/go-cryptonote-pool#5]
It would be nice to get the Pool hash rate in logs

**Comment by jorzhikgit** [comment]
how can i see log? or monitoring the pool ?

**Comment by sammy007** [comment]
Logs are on the screen, redirect to a file for analysis.

https://forum.getmonero.org/6/ideas/87023/solo-mining-stratum-for-monero-with-web-ui

**Comment by sammy007** [comment]
Web-UI included now.
