### ISSUE TITLE
New block failes first share 

### ISSUE THREAD

**Issue by marku89** [sammy007/go-cryptonote-pool#6]
Sometimes its happen that the new block wont transmitted to the miner fast enough, so i get stale shares. Is there a way so prevent this ? Pool or miner issue ?

Does it matters that my server and miner not in the same timezone an have some offset ?

2016/11/10 16:35:51 Valid share at difficulty 4000/20010
2016/11/10 16:35:52 New block to mine at height 1176710, diff: 2823802313, prev_hash: 562537548e20340bdb35667d31f7ec63182041fc704a22e9e5158cd286b784e4
2016/11/10 16:35:52 Broadcasting new jobs to 2 miners
2016/11/10 16:35:52 New block to mine at height 1176710, diff: 2823802313, prev_hash: 562537548e20340bdb35667d31f7ec63182041fc704a22e9e5158cd286b784e4
2016/11/10 16:35:52 Broadcasting new jobs to 1 miners
2016/11/10 16:35:52 Block expired for height 1176709 44Gpt5CDHmhQeQftKzzhdvUmJAwyZFgNZ2sjFQUoMKV5ditMwFRzLdh5jqiNj7XaTuaZpnscxepC3S7Hb2uMqWfw6EgmgQc@192.168.21.1
2016/11/10 16:35:53 New block to mine at height 1176710, diff: 2823802313, prev_hash: 562537548e20340bdb35667d31f7ec63182041fc704a22e9e5158cd286b784e4
2016/11/10 16:35:53 Broadcasting new jobs to 1 miners
2016/11/10 16:35:54 Valid share at difficulty 4000/4567

MINER !!
[2016-11-11 06:38:11] accepted: 121/121 (100.00%), 221.23 H/s at diff 1000 (yay!!!)
[2016-11-11 06:38:15] Stratum detected new block
[2016-11-11 06:38:15] accepted: 121/122 (99.18%), 226.99 H/s at diff 1000 (booooo)
[2016-11-11 06:38:16] accepted: 122/123 (99.19%), 218.71 H/s at diff 1000 (yay!!!)
[2016-11-11 06:38:18] accepted: 123/124 (99.19%), 221.38 H/s at diff 1000 (yay!!!)

**Comment by sammy007** [comment]
Stale share is stale share. It does not make any sense especially for solo miners. Timezone? It's network latency and also miner implementation details.

**Comment by marku89** [comment]
but its strange that the booooo cames after the new block, with the same miner on a public pool i have not this false shares

**Comment by sammy007** [comment]
Now it's not slow. All miners do the same.
